name: Python application

on:
  schedule:
    - cron: "11 5 * * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: echo "🍏 This job's status is ${{ job.status }}."
